services:
  - docker

before_script:
  # Ancient make binary at TravisCI doesn't support indentation with spaces
  - unexpand -t 4 Makefile > Makefile.tmp && mv Makefile.tmp Makefile

script:
  - make test

after_failure:
  - docker logs lucasvanlierop/containerization-workshop

after_success:
  - docker login --email=$DOCKER_EMAIL --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push lucasvanlierop/containerization-workshop:latest; fi

branches:
  only:
    - master
